server:
  port: 12138
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/blog_ya?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 2023++xy
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 5MB
  elasticsearch:
    uris: http://127.0.0.1:9200
    username: elastic
    password: HpqjL5GoQDmTRQxn4ZNm
mybatis-plus:
  configuration:
    # 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: yn
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto

oss:
  accessKey: JFVYIl_iyeE5SJ1ldrkEjYtCtelVWaWtBIuIVIfC
  secretKey: ggwbU2ao9dEbmaCQBv202AYug5uX_4hgGcEL6nIL
  bucket: blog-wow
  domainName: http://s10nnt6yg.hb-bkt.clouddn.com/